# Generated by Django 4.1.7 on 2023-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
